### ISSUE TITLE
获取对齐大小出现问题

### ISSUE THREAD

**Issue by august295** [genrwoody/convert_proto_struct#1]
我的结构体是
```cpp
enum PhoneType
{
	MOBILE = 0,
	HOME = 1,
	WORK = 2,
};
struct Phone
{
	std::string number;
	PhoneType type;
};
```
我的 proto 文件是
```protobuf
enum PhoneType
{
    MOBILE = 0;
    HOME   = 1;
    WORK   = 2;
}
message Phone
{
    string number  = 1;
    PhoneType type = 2;
}
```
没有使用 `#pragma pack()` 进行字节对齐，但我进行序列化时第一步计算字节时大小不对，实际应该是 `sizeof(Phone)=48`，但是计算后只有 `44`，导致第一步验证就不通过，请问我该怎么修改
![image](https://user-images.githubusercontent.com/45315371/174429042-e53a56d2-5ec7-472e-8ee7-fc5655866501.png)

**Comment by august295** [comment]
根据对齐标准，是因为不满足第三条
- 结构体变量的首地址能够被其对齐字节数大小所整除。
- 结构体每个成员相对结构体首地址的偏移都是成员大小的整数倍，如不满足，对前一个成员填充字节以满足。
- 结构体的总大小为结构体对齐字节数大小的整数倍，如不满足，最后填充字节以满足。

所以我在创建 `StructInfo` 的最后进行判断（在 101 左右添加判断），能够解决
![image](https://user-images.githubusercontent.com/45315371/174446505-bbf988ec-4a96-41bc-acc4-e121a3aa32dc.png)

**Comment by genrwoody** [comment]
@august295 谢谢反馈.
我使用了你的方法, 做了一点修正, 如下:
if (_size % _align) {
	_size += **_align -** _size % _align;
}
结构体转proto已经可以过了, 但是在proto转结构体时错误, 我在定位原因, 也许这几天会提交代码.

**Comment by genrwoody** [comment]
@august295 已修复, 请更新验证, 谢谢.
